### ISSUE TITLE
Problem on MacOSX

### ISSUE THREAD

**Issue by damiendoligez** [janestreet/ocaml_plugin#2]
I'm trying to install jenga 113.24.02 on MacOSX (through OPAM) and I get the following error when the build tries to call `ocaml-embed-compiler`:
```
(((pid 82207) (thread_id 0))
 ((human_readable 2016-03-11T13:07:28+0100)
  (int63_ns_since_epoch 1457698048822220000))
 "unhandled exception in Async scheduler"
 ("unhandled exception"
  ((src/monitor.ml.Error_
    ((exn
       "working_dir: none (cwd)\
      \nstatus: (Exit_non_zero 1)\
      \ncommand: (/bin/mkdir -p -m0700 -- /tmp)\
      \nmkdir: /tmp: Operation not permitted\
      \n")
     (backtrace
      ("Raised at file \"src/error.ml\", line 7, characters 20-30"
       "Called from file \"bin/ocaml_embed_compiler.ml\", line 5, characters 43-67"
       "Called from file \"src/deferred0.ml\", line 65, characters 64-69"
       "Called from file \"src/job_queue.ml\", line 160, characters 6-47" ""))
     (monitor
      (((name main) (here ()) (id 1) (has_seen_error true)
        (is_detached false))))))
   ((pid 82207) (thread_id 2)))))
```

This is because on MacOSX `/tmp` is a symlink to `/private/tmp`, so you can't do
```mkdir -p /tmp```
What you *can* do (and it should work on Linux too) is:
```mkdir -p /tmp/.```

I'm not sure if this should be fixed in `ocaml_plugin` or in `ocaml-embed-compiler`.

**Comment by mbarbin** [comment]
Thank you for reporting this.  We have a fix for this on the way.  We'll keep you updated of progress toward public release.

**Comment by trefis** [comment]
@mbarbin's fix just made its way here; it will be part of the next opam release.
Thanks again for the report!
